version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspace" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths: 
             - echo-output
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A texan's howdy"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspace" ]]; then
            echo "It workded!";
          else
            echo "Nope!" ; exit 1
          fi
  three:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A Hello from Hedera"
      - attach_workspace:
          at: my_workspace
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspace" ]]; then
            echo "It workded!";
          else
            echo "Nope!" ; exit 1
          fi
workflows:
  version: 2
  one_to_three:
    jobs:
      - one
      - two:
         requires: 
           - one
      - three
      
